# Generated by Django 3.2.19 on 2023-05-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('phrase', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('id_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_page.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('desc', models.TextField()),
                ('winrate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.TextField(unique=True)),
                ('name', models.TextField(unique=True)),
                ('id_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_page.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avg_kills', models.IntegerField()),
                ('winrate', models.TextField()),
                ('rating', models.IntegerField()),
                ('champions', models.ManyToManyField(through='sql_page.InfoAll', to='sql_page.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_page.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsChampions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_page.champion')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_page.items')),
            ],
        ),
        migrations.AddField(
            model_name='infoall',
            name='id_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_page.statistics'),
        ),
        migrations.AddField(
            model_name='infoall',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_page.user'),
        ),
    ]
