# Generated by Django 3.2.19 on 2023-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoall',
            old_name='id_champion',
            new_name='champion',
        ),
        migrations.RenameField(
            model_name='infoall',
            old_name='id_statistics',
            new_name='statistics',
        ),
        migrations.RenameField(
            model_name='infoall',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='itemschampions',
            old_name='id_champion',
            new_name='champion',
        ),
        migrations.RenameField(
            model_name='itemschampions',
            old_name='id_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='id_champion',
            new_name='champion',
        ),
        migrations.AlterField(
            model_name='champion',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='phrase',
            field=models.TextField(null=True),
        ),
    ]
