# Generated by Django 3.2.19 on 2023-05-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_page', '0005_alter_statistics_winrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemschampions',
            unique_together={('champion', 'item')},
        ),
    ]
