# Generated by Django 3.2.19 on 2023-05-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_page', '0006_alter_itemschampions_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='infoall',
            unique_together={('user', 'champion', 'season')},
        ),
    ]
